
 // This code was generated by a tool. Any changes made manually will be lost
 // the next time this code is regenerated.
 // 
  
 using System.Reflection;

 [assembly: AssemblyVersion("1.33.0.3")]
 [assembly: AssemblyFileVersion("1.33.0.3")]
 [assembly: KSPAssembly("DeepFreeze", 1, 33)]
